<?php
/**
 * DefinitionConfigurationsApi
 * PHP version 8.1
 *
 * @category Class
 * @package  HubSpot\Client\Crm\Associations\V4\Schema
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * CRM Associations Schema
 *
 * Basepom for all HubSpot Projects
 *
 * The version of the OpenAPI document: v4
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.19.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace HubSpot\Client\Crm\Associations\V4\Schema\Api;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\ConnectException;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use Psr\Http\Message\RequestInterface;
use Psr\Http\Message\ResponseInterface;
use HubSpot\Client\Crm\Associations\V4\Schema\ApiException;
use HubSpot\Client\Crm\Associations\V4\Schema\Configuration;
use HubSpot\Client\Crm\Associations\V4\Schema\FormDataProcessor;
use HubSpot\Client\Crm\Associations\V4\Schema\HeaderSelector;
use HubSpot\Client\Crm\Associations\V4\Schema\ObjectSerializer;

/**
 * DefinitionConfigurationsApi Class Doc Comment
 *
 * @category Class
 * @package  HubSpot\Client\Crm\Associations\V4\Schema
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class DefinitionConfigurationsApi
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @var int Host index
     */
    protected $hostIndex;

    /** @var string[] $contentTypes **/
    public const contentTypes = [
        'batchCreate' => [
            'application/json',
        ],
        'batchRemove' => [
            'application/json',
        ],
        'batchUpdate' => [
            'application/json',
        ],
        'getPage' => [
            'application/json',
        ],
        'getPageBetweenTwoObjectTypes' => [
            'application/json',
        ],
    ];

    /**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     * @param int             $hostIndex (Optional) host index to select the list of hosts if defined in the OpenAPI spec
     */
    public function __construct(
        ?ClientInterface $client = null,
        ?Configuration $config = null,
        ?HeaderSelector $selector = null,
        int $hostIndex = 0
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: Configuration::getDefaultConfiguration();
        $this->headerSelector = $selector ?: new HeaderSelector();
        $this->hostIndex = $hostIndex;
    }

    /**
     * Set the host index
     *
     * @param int $hostIndex Host index (required)
     */
    public function setHostIndex($hostIndex): void
    {
        $this->hostIndex = $hostIndex;
    }

    /**
     * Get the host index
     *
     * @return int Host index
     */
    public function getHostIndex()
    {
        return $this->hostIndex;
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation batchCreate
     *
     * Batch create association definitions between two object types.
     *
     * @param  string $from_object_type The type of the source object in the association. (required)
     * @param  string $to_object_type The type of the target object in the association. (required)
     * @param  \HubSpot\Client\Crm\Associations\V4\Schema\Model\BatchInputPublicAssociationDefinitionConfigurationCreateRequest $batch_input_public_association_definition_configuration_create_request batch_input_public_association_definition_configuration_create_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['batchCreate'] to see the possible values for this operation
     *
     * @throws \HubSpot\Client\Crm\Associations\V4\Schema\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \HubSpot\Client\Crm\Associations\V4\Schema\Model\BatchResponsePublicAssociationDefinitionUserConfiguration|\HubSpot\Client\Crm\Associations\V4\Schema\Model\Error
     */
    public function batchCreate($from_object_type, $to_object_type, $batch_input_public_association_definition_configuration_create_request, string $contentType = self::contentTypes['batchCreate'][0])
    {
        list($response) = $this->batchCreateWithHttpInfo($from_object_type, $to_object_type, $batch_input_public_association_definition_configuration_create_request, $contentType);
        return $response;
    }

    /**
     * Operation batchCreateWithHttpInfo
     *
     * Batch create association definitions between two object types.
     *
     * @param  string $from_object_type The type of the source object in the association. (required)
     * @param  string $to_object_type The type of the target object in the association. (required)
     * @param  \HubSpot\Client\Crm\Associations\V4\Schema\Model\BatchInputPublicAssociationDefinitionConfigurationCreateRequest $batch_input_public_association_definition_configuration_create_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['batchCreate'] to see the possible values for this operation
     *
     * @throws \HubSpot\Client\Crm\Associations\V4\Schema\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \HubSpot\Client\Crm\Associations\V4\Schema\Model\BatchResponsePublicAssociationDefinitionUserConfiguration|\HubSpot\Client\Crm\Associations\V4\Schema\Model\Error, HTTP status code, HTTP response headers (array of strings)
     */
    public function batchCreateWithHttpInfo($from_object_type, $to_object_type, $batch_input_public_association_definition_configuration_create_request, string $contentType = self::contentTypes['batchCreate'][0])
    {
        $request = $this->batchCreateRequest($from_object_type, $to_object_type, $batch_input_public_association_definition_configuration_create_request, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\HubSpot\Client\Crm\Associations\V4\Schema\Model\BatchResponsePublicAssociationDefinitionUserConfiguration',
                        $request,
                        $response,
                    );
                default:
                    return $this->handleResponseWithDataType(
                        '\HubSpot\Client\Crm\Associations\V4\Schema\Model\Error',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\HubSpot\Client\Crm\Associations\V4\Schema\Model\BatchResponsePublicAssociationDefinitionUserConfiguration',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\HubSpot\Client\Crm\Associations\V4\Schema\Model\BatchResponsePublicAssociationDefinitionUserConfiguration',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                default:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\HubSpot\Client\Crm\Associations\V4\Schema\Model\Error',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation batchCreateAsync
     *
     * Batch create association definitions between two object types.
     *
     * @param  string $from_object_type The type of the source object in the association. (required)
     * @param  string $to_object_type The type of the target object in the association. (required)
     * @param  \HubSpot\Client\Crm\Associations\V4\Schema\Model\BatchInputPublicAssociationDefinitionConfigurationCreateRequest $batch_input_public_association_definition_configuration_create_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['batchCreate'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function batchCreateAsync($from_object_type, $to_object_type, $batch_input_public_association_definition_configuration_create_request, string $contentType = self::contentTypes['batchCreate'][0])
    {
        return $this->batchCreateAsyncWithHttpInfo($from_object_type, $to_object_type, $batch_input_public_association_definition_configuration_create_request, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation batchCreateAsyncWithHttpInfo
     *
     * Batch create association definitions between two object types.
     *
     * @param  string $from_object_type The type of the source object in the association. (required)
     * @param  string $to_object_type The type of the target object in the association. (required)
     * @param  \HubSpot\Client\Crm\Associations\V4\Schema\Model\BatchInputPublicAssociationDefinitionConfigurationCreateRequest $batch_input_public_association_definition_configuration_create_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['batchCreate'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function batchCreateAsyncWithHttpInfo($from_object_type, $to_object_type, $batch_input_public_association_definition_configuration_create_request, string $contentType = self::contentTypes['batchCreate'][0])
    {
        $returnType = '\HubSpot\Client\Crm\Associations\V4\Schema\Model\BatchResponsePublicAssociationDefinitionUserConfiguration';
        $request = $this->batchCreateRequest($from_object_type, $to_object_type, $batch_input_public_association_definition_configuration_create_request, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'batchCreate'
     *
     * @param  string $from_object_type The type of the source object in the association. (required)
     * @param  string $to_object_type The type of the target object in the association. (required)
     * @param  \HubSpot\Client\Crm\Associations\V4\Schema\Model\BatchInputPublicAssociationDefinitionConfigurationCreateRequest $batch_input_public_association_definition_configuration_create_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['batchCreate'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function batchCreateRequest($from_object_type, $to_object_type, $batch_input_public_association_definition_configuration_create_request, string $contentType = self::contentTypes['batchCreate'][0])
    {

        // verify the required parameter 'from_object_type' is set
        if ($from_object_type === null || (is_array($from_object_type) && count($from_object_type) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $from_object_type when calling batchCreate'
            );
        }

        // verify the required parameter 'to_object_type' is set
        if ($to_object_type === null || (is_array($to_object_type) && count($to_object_type) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $to_object_type when calling batchCreate'
            );
        }

        // verify the required parameter 'batch_input_public_association_definition_configuration_create_request' is set
        if ($batch_input_public_association_definition_configuration_create_request === null || (is_array($batch_input_public_association_definition_configuration_create_request) && count($batch_input_public_association_definition_configuration_create_request) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $batch_input_public_association_definition_configuration_create_request when calling batchCreate'
            );
        }


        $resourcePath = '/crm/associations/v4/definitions/configurations/{fromObjectType}/{toObjectType}/batch/create';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // path params
        if ($from_object_type !== null) {
            $resourcePath = str_replace(
                '{' . 'fromObjectType' . '}',
                ObjectSerializer::toPathValue($from_object_type),
                $resourcePath
            );
        }
        // path params
        if ($to_object_type !== null) {
            $resourcePath = str_replace(
                '{' . 'toObjectType' . '}',
                ObjectSerializer::toPathValue($to_object_type),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', '*/*', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (isset($batch_input_public_association_definition_configuration_create_request)) {
            if (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the body
                $httpBody = \GuzzleHttp\Utils::jsonEncode(ObjectSerializer::sanitizeForSerialization($batch_input_public_association_definition_configuration_create_request));
            } else {
                $httpBody = $batch_input_public_association_definition_configuration_create_request;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires OAuth (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'POST',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation batchRemove
     *
     * Remove multiple association configurations between two specified object types in a batch operation.
     *
     * @param  string $from_object_type The type of the source object in the association. (required)
     * @param  string $to_object_type The type of the target object in the association. (required)
     * @param  \HubSpot\Client\Crm\Associations\V4\Schema\Model\BatchInputPublicAssociationSpec $batch_input_public_association_spec batch_input_public_association_spec (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['batchRemove'] to see the possible values for this operation
     *
     * @throws \HubSpot\Client\Crm\Associations\V4\Schema\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \HubSpot\Client\Crm\Associations\V4\Schema\Model\BatchResponseVoid|\HubSpot\Client\Crm\Associations\V4\Schema\Model\Error
     */
    public function batchRemove($from_object_type, $to_object_type, $batch_input_public_association_spec, string $contentType = self::contentTypes['batchRemove'][0])
    {
        list($response) = $this->batchRemoveWithHttpInfo($from_object_type, $to_object_type, $batch_input_public_association_spec, $contentType);
        return $response;
    }

    /**
     * Operation batchRemoveWithHttpInfo
     *
     * Remove multiple association configurations between two specified object types in a batch operation.
     *
     * @param  string $from_object_type The type of the source object in the association. (required)
     * @param  string $to_object_type The type of the target object in the association. (required)
     * @param  \HubSpot\Client\Crm\Associations\V4\Schema\Model\BatchInputPublicAssociationSpec $batch_input_public_association_spec (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['batchRemove'] to see the possible values for this operation
     *
     * @throws \HubSpot\Client\Crm\Associations\V4\Schema\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \HubSpot\Client\Crm\Associations\V4\Schema\Model\BatchResponseVoid|\HubSpot\Client\Crm\Associations\V4\Schema\Model\Error, HTTP status code, HTTP response headers (array of strings)
     */
    public function batchRemoveWithHttpInfo($from_object_type, $to_object_type, $batch_input_public_association_spec, string $contentType = self::contentTypes['batchRemove'][0])
    {
        $request = $this->batchRemoveRequest($from_object_type, $to_object_type, $batch_input_public_association_spec, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\HubSpot\Client\Crm\Associations\V4\Schema\Model\BatchResponseVoid',
                        $request,
                        $response,
                    );
                default:
                    return $this->handleResponseWithDataType(
                        '\HubSpot\Client\Crm\Associations\V4\Schema\Model\Error',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\HubSpot\Client\Crm\Associations\V4\Schema\Model\BatchResponseVoid',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\HubSpot\Client\Crm\Associations\V4\Schema\Model\BatchResponseVoid',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                default:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\HubSpot\Client\Crm\Associations\V4\Schema\Model\Error',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation batchRemoveAsync
     *
     * Remove multiple association configurations between two specified object types in a batch operation.
     *
     * @param  string $from_object_type The type of the source object in the association. (required)
     * @param  string $to_object_type The type of the target object in the association. (required)
     * @param  \HubSpot\Client\Crm\Associations\V4\Schema\Model\BatchInputPublicAssociationSpec $batch_input_public_association_spec (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['batchRemove'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function batchRemoveAsync($from_object_type, $to_object_type, $batch_input_public_association_spec, string $contentType = self::contentTypes['batchRemove'][0])
    {
        return $this->batchRemoveAsyncWithHttpInfo($from_object_type, $to_object_type, $batch_input_public_association_spec, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation batchRemoveAsyncWithHttpInfo
     *
     * Remove multiple association configurations between two specified object types in a batch operation.
     *
     * @param  string $from_object_type The type of the source object in the association. (required)
     * @param  string $to_object_type The type of the target object in the association. (required)
     * @param  \HubSpot\Client\Crm\Associations\V4\Schema\Model\BatchInputPublicAssociationSpec $batch_input_public_association_spec (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['batchRemove'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function batchRemoveAsyncWithHttpInfo($from_object_type, $to_object_type, $batch_input_public_association_spec, string $contentType = self::contentTypes['batchRemove'][0])
    {
        $returnType = '\HubSpot\Client\Crm\Associations\V4\Schema\Model\BatchResponseVoid';
        $request = $this->batchRemoveRequest($from_object_type, $to_object_type, $batch_input_public_association_spec, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'batchRemove'
     *
     * @param  string $from_object_type The type of the source object in the association. (required)
     * @param  string $to_object_type The type of the target object in the association. (required)
     * @param  \HubSpot\Client\Crm\Associations\V4\Schema\Model\BatchInputPublicAssociationSpec $batch_input_public_association_spec (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['batchRemove'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function batchRemoveRequest($from_object_type, $to_object_type, $batch_input_public_association_spec, string $contentType = self::contentTypes['batchRemove'][0])
    {

        // verify the required parameter 'from_object_type' is set
        if ($from_object_type === null || (is_array($from_object_type) && count($from_object_type) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $from_object_type when calling batchRemove'
            );
        }

        // verify the required parameter 'to_object_type' is set
        if ($to_object_type === null || (is_array($to_object_type) && count($to_object_type) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $to_object_type when calling batchRemove'
            );
        }

        // verify the required parameter 'batch_input_public_association_spec' is set
        if ($batch_input_public_association_spec === null || (is_array($batch_input_public_association_spec) && count($batch_input_public_association_spec) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $batch_input_public_association_spec when calling batchRemove'
            );
        }


        $resourcePath = '/crm/associations/v4/definitions/configurations/{fromObjectType}/{toObjectType}/batch/purge';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // path params
        if ($from_object_type !== null) {
            $resourcePath = str_replace(
                '{' . 'fromObjectType' . '}',
                ObjectSerializer::toPathValue($from_object_type),
                $resourcePath
            );
        }
        // path params
        if ($to_object_type !== null) {
            $resourcePath = str_replace(
                '{' . 'toObjectType' . '}',
                ObjectSerializer::toPathValue($to_object_type),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', '*/*', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (isset($batch_input_public_association_spec)) {
            if (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the body
                $httpBody = \GuzzleHttp\Utils::jsonEncode(ObjectSerializer::sanitizeForSerialization($batch_input_public_association_spec));
            } else {
                $httpBody = $batch_input_public_association_spec;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires OAuth (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'POST',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation batchUpdate
     *
     * Batch update association configurations between two object types.
     *
     * @param  string $from_object_type The type of the source object in the association. (required)
     * @param  string $to_object_type The type of the target object in the association. (required)
     * @param  \HubSpot\Client\Crm\Associations\V4\Schema\Model\BatchInputPublicAssociationDefinitionConfigurationUpdateRequest $batch_input_public_association_definition_configuration_update_request batch_input_public_association_definition_configuration_update_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['batchUpdate'] to see the possible values for this operation
     *
     * @throws \HubSpot\Client\Crm\Associations\V4\Schema\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \HubSpot\Client\Crm\Associations\V4\Schema\Model\BatchResponsePublicAssociationDefinitionConfigurationUpdateResult|\HubSpot\Client\Crm\Associations\V4\Schema\Model\Error
     */
    public function batchUpdate($from_object_type, $to_object_type, $batch_input_public_association_definition_configuration_update_request, string $contentType = self::contentTypes['batchUpdate'][0])
    {
        list($response) = $this->batchUpdateWithHttpInfo($from_object_type, $to_object_type, $batch_input_public_association_definition_configuration_update_request, $contentType);
        return $response;
    }

    /**
     * Operation batchUpdateWithHttpInfo
     *
     * Batch update association configurations between two object types.
     *
     * @param  string $from_object_type The type of the source object in the association. (required)
     * @param  string $to_object_type The type of the target object in the association. (required)
     * @param  \HubSpot\Client\Crm\Associations\V4\Schema\Model\BatchInputPublicAssociationDefinitionConfigurationUpdateRequest $batch_input_public_association_definition_configuration_update_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['batchUpdate'] to see the possible values for this operation
     *
     * @throws \HubSpot\Client\Crm\Associations\V4\Schema\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \HubSpot\Client\Crm\Associations\V4\Schema\Model\BatchResponsePublicAssociationDefinitionConfigurationUpdateResult|\HubSpot\Client\Crm\Associations\V4\Schema\Model\Error, HTTP status code, HTTP response headers (array of strings)
     */
    public function batchUpdateWithHttpInfo($from_object_type, $to_object_type, $batch_input_public_association_definition_configuration_update_request, string $contentType = self::contentTypes['batchUpdate'][0])
    {
        $request = $this->batchUpdateRequest($from_object_type, $to_object_type, $batch_input_public_association_definition_configuration_update_request, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\HubSpot\Client\Crm\Associations\V4\Schema\Model\BatchResponsePublicAssociationDefinitionConfigurationUpdateResult',
                        $request,
                        $response,
                    );
                default:
                    return $this->handleResponseWithDataType(
                        '\HubSpot\Client\Crm\Associations\V4\Schema\Model\Error',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\HubSpot\Client\Crm\Associations\V4\Schema\Model\BatchResponsePublicAssociationDefinitionConfigurationUpdateResult',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\HubSpot\Client\Crm\Associations\V4\Schema\Model\BatchResponsePublicAssociationDefinitionConfigurationUpdateResult',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                default:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\HubSpot\Client\Crm\Associations\V4\Schema\Model\Error',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation batchUpdateAsync
     *
     * Batch update association configurations between two object types.
     *
     * @param  string $from_object_type The type of the source object in the association. (required)
     * @param  string $to_object_type The type of the target object in the association. (required)
     * @param  \HubSpot\Client\Crm\Associations\V4\Schema\Model\BatchInputPublicAssociationDefinitionConfigurationUpdateRequest $batch_input_public_association_definition_configuration_update_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['batchUpdate'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function batchUpdateAsync($from_object_type, $to_object_type, $batch_input_public_association_definition_configuration_update_request, string $contentType = self::contentTypes['batchUpdate'][0])
    {
        return $this->batchUpdateAsyncWithHttpInfo($from_object_type, $to_object_type, $batch_input_public_association_definition_configuration_update_request, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation batchUpdateAsyncWithHttpInfo
     *
     * Batch update association configurations between two object types.
     *
     * @param  string $from_object_type The type of the source object in the association. (required)
     * @param  string $to_object_type The type of the target object in the association. (required)
     * @param  \HubSpot\Client\Crm\Associations\V4\Schema\Model\BatchInputPublicAssociationDefinitionConfigurationUpdateRequest $batch_input_public_association_definition_configuration_update_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['batchUpdate'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function batchUpdateAsyncWithHttpInfo($from_object_type, $to_object_type, $batch_input_public_association_definition_configuration_update_request, string $contentType = self::contentTypes['batchUpdate'][0])
    {
        $returnType = '\HubSpot\Client\Crm\Associations\V4\Schema\Model\BatchResponsePublicAssociationDefinitionConfigurationUpdateResult';
        $request = $this->batchUpdateRequest($from_object_type, $to_object_type, $batch_input_public_association_definition_configuration_update_request, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'batchUpdate'
     *
     * @param  string $from_object_type The type of the source object in the association. (required)
     * @param  string $to_object_type The type of the target object in the association. (required)
     * @param  \HubSpot\Client\Crm\Associations\V4\Schema\Model\BatchInputPublicAssociationDefinitionConfigurationUpdateRequest $batch_input_public_association_definition_configuration_update_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['batchUpdate'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function batchUpdateRequest($from_object_type, $to_object_type, $batch_input_public_association_definition_configuration_update_request, string $contentType = self::contentTypes['batchUpdate'][0])
    {

        // verify the required parameter 'from_object_type' is set
        if ($from_object_type === null || (is_array($from_object_type) && count($from_object_type) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $from_object_type when calling batchUpdate'
            );
        }

        // verify the required parameter 'to_object_type' is set
        if ($to_object_type === null || (is_array($to_object_type) && count($to_object_type) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $to_object_type when calling batchUpdate'
            );
        }

        // verify the required parameter 'batch_input_public_association_definition_configuration_update_request' is set
        if ($batch_input_public_association_definition_configuration_update_request === null || (is_array($batch_input_public_association_definition_configuration_update_request) && count($batch_input_public_association_definition_configuration_update_request) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $batch_input_public_association_definition_configuration_update_request when calling batchUpdate'
            );
        }


        $resourcePath = '/crm/associations/v4/definitions/configurations/{fromObjectType}/{toObjectType}/batch/update';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // path params
        if ($from_object_type !== null) {
            $resourcePath = str_replace(
                '{' . 'fromObjectType' . '}',
                ObjectSerializer::toPathValue($from_object_type),
                $resourcePath
            );
        }
        // path params
        if ($to_object_type !== null) {
            $resourcePath = str_replace(
                '{' . 'toObjectType' . '}',
                ObjectSerializer::toPathValue($to_object_type),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', '*/*', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (isset($batch_input_public_association_definition_configuration_update_request)) {
            if (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the body
                $httpBody = \GuzzleHttp\Utils::jsonEncode(ObjectSerializer::sanitizeForSerialization($batch_input_public_association_definition_configuration_update_request));
            } else {
                $httpBody = $batch_input_public_association_definition_configuration_update_request;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires OAuth (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'POST',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation getPage
     *
     * Retrieve all association configuration definitions.
     *
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getPage'] to see the possible values for this operation
     *
     * @throws \HubSpot\Client\Crm\Associations\V4\Schema\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \HubSpot\Client\Crm\Associations\V4\Schema\Model\CollectionResponsePublicAssociationDefinitionUserConfiguration|\HubSpot\Client\Crm\Associations\V4\Schema\Model\Error
     */
    public function getPage(string $contentType = self::contentTypes['getPage'][0])
    {
        list($response) = $this->getPageWithHttpInfo($contentType);
        return $response;
    }

    /**
     * Operation getPageWithHttpInfo
     *
     * Retrieve all association configuration definitions.
     *
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getPage'] to see the possible values for this operation
     *
     * @throws \HubSpot\Client\Crm\Associations\V4\Schema\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \HubSpot\Client\Crm\Associations\V4\Schema\Model\CollectionResponsePublicAssociationDefinitionUserConfiguration|\HubSpot\Client\Crm\Associations\V4\Schema\Model\Error, HTTP status code, HTTP response headers (array of strings)
     */
    public function getPageWithHttpInfo(string $contentType = self::contentTypes['getPage'][0])
    {
        $request = $this->getPageRequest($contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\HubSpot\Client\Crm\Associations\V4\Schema\Model\CollectionResponsePublicAssociationDefinitionUserConfiguration',
                        $request,
                        $response,
                    );
                default:
                    return $this->handleResponseWithDataType(
                        '\HubSpot\Client\Crm\Associations\V4\Schema\Model\Error',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\HubSpot\Client\Crm\Associations\V4\Schema\Model\CollectionResponsePublicAssociationDefinitionUserConfiguration',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\HubSpot\Client\Crm\Associations\V4\Schema\Model\CollectionResponsePublicAssociationDefinitionUserConfiguration',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                default:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\HubSpot\Client\Crm\Associations\V4\Schema\Model\Error',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation getPageAsync
     *
     * Retrieve all association configuration definitions.
     *
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getPage'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getPageAsync(string $contentType = self::contentTypes['getPage'][0])
    {
        return $this->getPageAsyncWithHttpInfo($contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation getPageAsyncWithHttpInfo
     *
     * Retrieve all association configuration definitions.
     *
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getPage'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getPageAsyncWithHttpInfo(string $contentType = self::contentTypes['getPage'][0])
    {
        $returnType = '\HubSpot\Client\Crm\Associations\V4\Schema\Model\CollectionResponsePublicAssociationDefinitionUserConfiguration';
        $request = $this->getPageRequest($contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'getPage'
     *
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getPage'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function getPageRequest(string $contentType = self::contentTypes['getPage'][0])
    {


        $resourcePath = '/crm/associations/v4/definitions/configurations/all';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;





        $headers = $this->headerSelector->selectHeaders(
            ['application/json', '*/*', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires OAuth (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation getPageBetweenTwoObjectTypes
     *
     * Retrieve configuration details for associations between two object types.
     *
     * @param  string $from_object_type The type of the source object in the association. (required)
     * @param  string $to_object_type The type of the target object in the association. (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getPageBetweenTwoObjectTypes'] to see the possible values for this operation
     *
     * @throws \HubSpot\Client\Crm\Associations\V4\Schema\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \HubSpot\Client\Crm\Associations\V4\Schema\Model\CollectionResponsePublicAssociationDefinitionUserConfiguration|\HubSpot\Client\Crm\Associations\V4\Schema\Model\Error
     */
    public function getPageBetweenTwoObjectTypes($from_object_type, $to_object_type, string $contentType = self::contentTypes['getPageBetweenTwoObjectTypes'][0])
    {
        list($response) = $this->getPageBetweenTwoObjectTypesWithHttpInfo($from_object_type, $to_object_type, $contentType);
        return $response;
    }

    /**
     * Operation getPageBetweenTwoObjectTypesWithHttpInfo
     *
     * Retrieve configuration details for associations between two object types.
     *
     * @param  string $from_object_type The type of the source object in the association. (required)
     * @param  string $to_object_type The type of the target object in the association. (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getPageBetweenTwoObjectTypes'] to see the possible values for this operation
     *
     * @throws \HubSpot\Client\Crm\Associations\V4\Schema\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \HubSpot\Client\Crm\Associations\V4\Schema\Model\CollectionResponsePublicAssociationDefinitionUserConfiguration|\HubSpot\Client\Crm\Associations\V4\Schema\Model\Error, HTTP status code, HTTP response headers (array of strings)
     */
    public function getPageBetweenTwoObjectTypesWithHttpInfo($from_object_type, $to_object_type, string $contentType = self::contentTypes['getPageBetweenTwoObjectTypes'][0])
    {
        $request = $this->getPageBetweenTwoObjectTypesRequest($from_object_type, $to_object_type, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\HubSpot\Client\Crm\Associations\V4\Schema\Model\CollectionResponsePublicAssociationDefinitionUserConfiguration',
                        $request,
                        $response,
                    );
                default:
                    return $this->handleResponseWithDataType(
                        '\HubSpot\Client\Crm\Associations\V4\Schema\Model\Error',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\HubSpot\Client\Crm\Associations\V4\Schema\Model\CollectionResponsePublicAssociationDefinitionUserConfiguration',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\HubSpot\Client\Crm\Associations\V4\Schema\Model\CollectionResponsePublicAssociationDefinitionUserConfiguration',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                default:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\HubSpot\Client\Crm\Associations\V4\Schema\Model\Error',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation getPageBetweenTwoObjectTypesAsync
     *
     * Retrieve configuration details for associations between two object types.
     *
     * @param  string $from_object_type The type of the source object in the association. (required)
     * @param  string $to_object_type The type of the target object in the association. (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getPageBetweenTwoObjectTypes'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getPageBetweenTwoObjectTypesAsync($from_object_type, $to_object_type, string $contentType = self::contentTypes['getPageBetweenTwoObjectTypes'][0])
    {
        return $this->getPageBetweenTwoObjectTypesAsyncWithHttpInfo($from_object_type, $to_object_type, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation getPageBetweenTwoObjectTypesAsyncWithHttpInfo
     *
     * Retrieve configuration details for associations between two object types.
     *
     * @param  string $from_object_type The type of the source object in the association. (required)
     * @param  string $to_object_type The type of the target object in the association. (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getPageBetweenTwoObjectTypes'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getPageBetweenTwoObjectTypesAsyncWithHttpInfo($from_object_type, $to_object_type, string $contentType = self::contentTypes['getPageBetweenTwoObjectTypes'][0])
    {
        $returnType = '\HubSpot\Client\Crm\Associations\V4\Schema\Model\CollectionResponsePublicAssociationDefinitionUserConfiguration';
        $request = $this->getPageBetweenTwoObjectTypesRequest($from_object_type, $to_object_type, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'getPageBetweenTwoObjectTypes'
     *
     * @param  string $from_object_type The type of the source object in the association. (required)
     * @param  string $to_object_type The type of the target object in the association. (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getPageBetweenTwoObjectTypes'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function getPageBetweenTwoObjectTypesRequest($from_object_type, $to_object_type, string $contentType = self::contentTypes['getPageBetweenTwoObjectTypes'][0])
    {

        // verify the required parameter 'from_object_type' is set
        if ($from_object_type === null || (is_array($from_object_type) && count($from_object_type) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $from_object_type when calling getPageBetweenTwoObjectTypes'
            );
        }

        // verify the required parameter 'to_object_type' is set
        if ($to_object_type === null || (is_array($to_object_type) && count($to_object_type) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $to_object_type when calling getPageBetweenTwoObjectTypes'
            );
        }


        $resourcePath = '/crm/associations/v4/definitions/configurations/{fromObjectType}/{toObjectType}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // path params
        if ($from_object_type !== null) {
            $resourcePath = str_replace(
                '{' . 'fromObjectType' . '}',
                ObjectSerializer::toPathValue($from_object_type),
                $resourcePath
            );
        }
        // path params
        if ($to_object_type !== null) {
            $resourcePath = str_replace(
                '{' . 'toObjectType' . '}',
                ObjectSerializer::toPathValue($to_object_type),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', '*/*', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires OAuth (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        if ($this->config->getCertFile()) {
            $options[RequestOptions::CERT] = $this->config->getCertFile();
        }

        if ($this->config->getKeyFile()) {
            $options[RequestOptions::SSL_KEY] = $this->config->getKeyFile();
        }

        return $options;
    }

    private function handleResponseWithDataType(
        string $dataType,
        RequestInterface $request,
        ResponseInterface $response
    ): array {
        if ($dataType === '\SplFileObject') {
            $content = $response->getBody(); //stream goes to serializer
        } else {
            $content = (string) $response->getBody();
            if ($dataType !== 'string') {
                try {
                    $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                } catch (\JsonException $exception) {
                    throw new ApiException(
                        sprintf(
                            'Error JSON decoding server response (%s)',
                            $request->getUri()
                        ),
                        $response->getStatusCode(),
                        $response->getHeaders(),
                        $content
                    );
                }
            }
        }

        return [
            ObjectSerializer::deserialize($content, $dataType, []),
            $response->getStatusCode(),
            $response->getHeaders()
        ];
    }

    private function responseWithinRangeCode(
        string $rangeCode,
        int $statusCode
    ): bool {
        $left = (int) ($rangeCode[0].'00');
        $right = (int) ($rangeCode[0].'99');

        return $statusCode >= $left && $statusCode <= $right;
    }
}
