name: phpspec

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      with:
        php-version: '8.0'
      - run: composer install
      - run: vendor/bin/phpspec run
